language: php
php:
  - 7.1

env:
  matrix:
    - LOWEST_DEPS=""
    - LOWEST_DEPS="--prefer-lowest"

services:
  - mysql

sudo: false

cache: vendor

before_script:
  - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - composer update --prefer-source $LOWEST_DEPS

script:
  - bin/atoum --configurations tests/.atoum.php --bootstrap-file tests/.bootstrap.atoum.php
  - bin/sabre-cs-fixer fix --dry-run --diff .

notifications:
  slack:
    rooms:
      secure: LVmBXAz0TKdB8dsB9Rt+M5+KnpStxEbOKuNVHN/lYOYmnB5CNogc/TDUKIFe5OUHAjGbn3xUy+tgBIME/RZLPAC6aAKpw0BPbGXYeagYlDBj9HUR9sUDrwV+l/75e4QWZPrUwS1dIa4ePirosIlYZwlwfGzEz8SgVY2x7BZFBEs=
    on_success: change
    on_failure: change
